modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-v3"

[[mods]]
modId = "moreloyaltrident"
version = "${version}"
displayName = "TheMoreLoyalTrident"
authors = "TeamPotato"
description = '''
A Minecraft Mod.
'''

[[dependencies.moreloyaltrident]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
